#ifndef __WTGAMESETTINGS_H__
#define __WTGAMESETTINGS_H__

//This File contains a lot of settings, values and variables.
//Making them #define commands means they only need to be updated here to update all instances in the program.
//This makes it much more reliable and easy to update settings for the program.
//Take a look at the INPUT variables beneath. See how they use both keys and mouse inputs.

//Collision Filters
#define PLAYER_SHIP_FILTER 1
//#define PLAYER_SHIELD_FILTER PLAYER_SHIP_FILTER+1
#define PLAYER_SHIELD_FILTER 0
#define PLAYER_WHOLE_CHECK PLAYER_SHIP_FILTER+2
#define LEVIATHAN_COMPONENT_FILTER 4
#define ENEMY_SHIP_FILTER 4
#define ENEMY_SHIELD_FILTER ENEMY_SHIP_FILTER+1
#define ENEMY_WHOLE_CHECK ENEMY_SHIP_FILTER+2
#define ENEMY_BULLET_FILTER 0
#define PLAYER_BULLET_FILTER 0
#define MISSILE_FILTER 7
#define CHAFF_FILTER 8

#define PLANNING_COMPONENT_FILTER 1

//Leviathan Component Types
#define LV_TURRET_VOID 0
#define LV_COMPONENT_VOID 0
#define LV_MULTIHULL 1
#define LV_VENT 2
#define LV_REACTOR 3
#define LV_THRUSTERS 4
#define LV_SENSORS 5
#define LV_TURRET_PROJECTILE 6
#define LV_TURRET_BEAM 7
#define LV_TURRET_MISSILE 8
#define LV_TURRET_TRACTOR 9
#define LV_SHIELD 10
#define LV_HULL 11
#define LV_REPAIR 12

//UserSignal Codes
#define DEAD_FIGHTER 1
#define BEAM_COLLISION 2
#define LEVIATHAN_COMPONENT_DEATH 3
#define LEVIATHAN_COMPONENT_KILL 4
#define LEVIATHAN_COMPONENT_FREE 1
#define DROP_SHIELDS 5
#define CHANGE_TREE_BASE 6
#define LEVIATHAN_REACTOR_DEATH 7
#define LEVIATHAN_POWER_STATE 8
#define EXPLOSION_COLLISION 9

#define LEVIATHAN_DAMAGE_PARTICLE_SPEED 0.4f

//Fighter Status'
#define FIGHTER_ATTACK 0
#define FIGHTER_FLEE 1

//General Settings
#define BULLET_DAMAGE 5.0f
#define BULLET_COLOR 1.0f,1.0f,0.0,1.0f
#define SHIELD_ALPHA 0.6f
#define PARTICLE_SPEED 0.05f
#define BULLET_SIZE 10.0f
#define MISSILE_HEALTH_BURN_RATE 0.04f
#define MISSILE_TYPES 5
#define MISSILE_TYPE_EXPLOSIVE 0
#define MISSILE_TYPE_LASER 1
#define MISSILE_TYPE_EMP 2
#define MISSILE_TYPE_CHAFF 3
#define MISSILE_TYPE_MW 4
#define MISSILE_TYPE_EMPTY MISSILE_TYPES
#define MISSILE_TYPE_VOID MISSILE_TYPES
#define MISSILE_EXPLOSIVE_COLOR cRGBA(1.0f,0.0f,0.0f,0.6f)
#define MISSILE_LASER_COLOR cRGBA(0.0f,0.0f,1.0f,0.6f)
#define MISSILE_EMP_COLOR cRGBA(0.0f,1.0f,0.0f,0.6f)
#define MISSILE_CHAFF_COLOR cRGBA(1.0f,1.0f,0.0f,0.6f)
#define MISSILE_MW_COLOR cRGBA(0.5f,0.5f,0.5f,0.6f)
#define MISSILE_EMPTY_COLOR cRGBA(0.0f,0.0f,0.0f,0.6f)

#define DAMAGE_TYPE_INSTANTANEOUS 0
#define DAMAGE_TYPE_CONTINUOUS 1
#define DAMAGE_TYPE_AREA 2

#define DAMAGE_TYPES 3
#define DAMAGE_TYPE_THROUGH (DAMAGE_TYPES+1)

#define CONTINUOUS_ARMOUR_FACTOR 1.0f

#define ENEMY_MISSILE_PASS_DELAY 2.0f
#define MISSILE_CHAFF_DELAY 20.0f
#define CHAFF_DELAY_ACTIVATE 3.0f

#define SMOKE_TRANSPARENCY 0.1f


//Camera Settings
#define CAMERA_FAR 100000.0f
#define CAMERA_NEAR 40.0f
#define CAMERA_WIDTH 20.0f
#define CAMERA_HEIGHT 15.0f
#define CAMERA_FOLLOW_DISTANCE -150.0f
#define CAMERA_OFFSET_DISTANCE -5.0f

#define PLANNING_CAMERA_WIDTH (CAMERA_WIDTH*(_WINDOW->RenderAreaWidth()-DATA_BOX_WIDTH)/_WINDOW->RenderAreaWidth())
#define PLANNING_CAMERA_HEIGHT CAMERA_HEIGHT

#define PLAYER_VIEWPORT_FAR CAMERA_FAR
#define PLAYER_VIEWPORT_NEAR CAMERA_NEAR
#define PLAYER_VIEWPORT_WIDTH 0.8f
#define PLAYER_VIEWPORT_HEIGHT 0.6f
#define PLAYER_VIEWPORT_OFFSET_Y -0.5f
#define PLAYER_VIEWPORT_OFFSET_Z 4.0f



//Fighter Settings
#define FIGHTER_HEALTH 20.0f
#define FIGHTER_SPEED 0.5f
#define FIGHTER_FLAMETRAILS 0.8f
#define FIGHTER_MAX_FLEE 150.0f
#define FIGHTER_RELOAD_TIME 0.4f
#define FIGHTER_BULLET_SPEED 15.0f
#define FIGHTER_FLEE_DISTANCE 10000
#define FIGHTER_ATTACK_DISTANCE 1000000
#define FIGHTER_FIRE_DISTANCE 5000000



//Player Display / GUI Settings.

#define PLAYER_MOVE_ICON_X gpWindow->RenderAreaWidth()-300.0f
#define PLAYER_MOVE_ICON_Y gpWindow->RenderAreaHeight()-75.0f
#define PLAYER_MOVE_ICON_WIDTH 100.0f
#define PLAYER_MOVE_ICON_HEIGHT 100.0f


#define LEVIATHAN_SELECTION_ROWS 20
#define LEVIATHAN_SELECTION_COLUMNS 6
#define LEVIATHAN_SELECTION_SIZE 30

#define LEVIATHAN_SELECTION_X 50.0f
#define LEVIATHAN_SELECTION_Y 450.0f
#define LEVIATHAN_SELECTION_MKS_STEP 100.0f
#define LEVIATHAN_SELECTION_MKS_SPACE 50.0f

#define PLAYER_HEALTH_DISPLAY_X 300.0f
#define PLAYER_HEALTH_DISPLAY_Y (_WINDOW->RenderAreaHeight()-100.0f)
#define PLAYER_HEALTH_DISPLAY_SIZE 50.0f

#define BATTLESCAPE_ICON_SIZE 15.0f

#define LOWER_SHIELD_DISPLAY_X 200.0f
#define LOWER_SHIELD_DISPLAY_Y (_WINDOW->RenderAreaHeight()-100.0f)
#define UPPER_SHIELD_DISPLAY_X 400.0f
#define UPPER_SHIELD_DISPLAY_Y (_WINDOW->RenderAreaHeight()-100.0f)
#define SHIELD_DISPLAY_SIZE (PLAYER_HEALTH_DISPLAY_SIZE*1.5f)

#define PLAYER_HEALTH_SCALE (1/PLAYER_MAX_HEALTH)
#define SLIDE_INDICATOR_MULTIPLIER 0.005f

#define SLIDE_DIAL_SIZE 100.0f
#define SLIDE_DIAL_X 100.0f
#define SLIDE_DIAL_Y (_WINDOW->RenderAreaHeight()-100.0f)

#define SHIP_TARGET_RETICULE_X (_WINDOW->RenderAreaWidth()/2)
#define SHIP_TARGET_RETICULE_Y (_WINDOW->RenderAreaHeight()/2)

#define SHIP_MISSILE_RACK_X (gpWindow->RenderAreaWidth()/2)
#define SHIP_MISSILE_RACK_Y (gpWindow->RenderAreaHeight()/2)
#define SHIP_MISSILE_RACK_SIZE 150.0f
#define SHIP_MISSIlE_SLOT_SIZE (SHIP_MISSILE_RACK_SIZE/(MISSILE_SLOTS+1))
#define SHIP_MISSILE_SLOT_RADIUS (SHIP_MISSILE_RACK_SIZE*0.37)

#define PLANNING_MISSILE_RACK_X 200.0f
#define PLANNING_MISSILE_RACK_Y 200.0f
#define PLANNING_MISSILE_RACK_SIZE 200.0f
#define PLANNING_MISSIlE_SLOT_SIZE (PLANNING_MISSILE_RACK_SIZE/(MISSILE_SLOTS+1))
#define PLANNING_MISSILE_SLOT_RADIUS (PLANNING_MISSILE_RACK_SIZE*0.37)

#define DATA_ITEM_HEIGHT 18.0f
#define DATA_BOX_WIDTH 350.0f

#define COMBAT_STATUS_BOX_WIDTH 300.0f
#define COMBAT_STATUS_BOX_HEIGHT 200.0f
#define COMBAT_STATUS_BOX_X (_WINDOW->RenderAreaWidth()-COMBAT_STATUS_BOX_WIDTH*0.5)
#define COMBAT_STATUS_BOX_Y 250.0f
#define COMBAT_STATUS_DISPLAY_WIDTH 25.0f
#define COMBAT_STATUS_DISPLAY_HEIGHT 25.0f
#define COMBAT_STATUS_DISPLAY_X (COMBAT_STATUS_BOX_X+COMBAT_STATUS_BOX_WIDTH*0.5-COMBAT_STATUS_DISPLAY_WIDTH)
#define COMBAT_STATUS_DISPLAY_Y_START (COMBAT_STATUS_BOX_Y+COMBAT_STATUS_BOX_HEIGHT*0.5-COMBAT_STATUS_BOX_HEIGHT*0.35)
#define COMBAT_STATUS_DISPLAY_Y_STEP (COMBAT_STATUS_DISPLAY_HEIGHT*1.125f)
#define COMBAT_STATUS_TEXT_X (COMBAT_STATUS_BOX_X-COMBAT_STATUS_BOX_WIDTH*0.5+COMBAT_STATUS_DISPLAY_WIDTH)

#define REACTOR_OVERLOAD_FACTOR 0.3

#define HULL_SOUND_DELAY 30

#define ACTIVATE_SOUND 0

#define PLANNING_SHIELD_COLOR cRGBA(0.0f,1.0f,0.0f,0.2f)
#define PLANNING_SHIELD_SELECTED_COLOR cRGBA(1.0f,1.0f,1.0f,0.2f)
#define PLANNING_FIRE_ARC_COLOR cRGBA(1.0f,0.0f,0.0f,0.2f)

#define PLANNING_ICON_SIZE fabs(40.0f*1000/_CAMERA->Z())

#define PLAYER_GUN_ICON_WIDTH 100
#define PLAYER_GUN_ICON_HEIGHT 100
#define PLAYER_GUN_ICON_X 400
#define PLAYER_GUN_ICON_Y 75
#define PLAYER_GUN_SIZING_WIDTH 25
#define PLAYER_GUN_SIZING_HEIGHT 25
#define PLAYER_BULLET_DAMAGE_SCALE 1.7


//Player Ship Settings
#define PLAYER_MAX_HEALTH 1000.0f

#define PLAYER_SHIELD_MAX 1000.0f
#define PLAYER_SHIELD_RECHARGE 0.12f
#define PLAYER_SHIELD_DELAY 500.0f
#define PLAYER_RELOAD_TIME 0.6f
#define PLAYER_MISSILE_RELOAD_TIME 40.0f

#define BULLET_RANGE 4000.0f
#define PLAYER_BULLET_SPEED 20.0f
#define PLAYER_BULLET_DAMAGE 5.0f
#define BULLET_THRUST 4.0f

#define BEAM_RECHARGE_RATE 0.0001f
#define BEAM_DISCHARGE_RATE 0.995f
#define BEAM_DAMAGE_MULTIPLIER 10.0f


#define PLAYER_BEAM_LENGTH 4000.0f
#define PLAYER_BEAM_WIDTH 0.5f
#define PLAYER_BEAM_OFFSET_Z 4.0f
#define PLAYER_BEAM_OFFSET_Y 0.5f
#define BEAM_SEGMENTS 16

#define THRUST_CHANGE_DELAY 24
#define THRUST_LIMIT 1.0f
#define INST_THRUST 80.0f
#define NON_DIRECT_THRUST 0.5f
#define SPEED_LIMIT 2000.0f
#define SLIDE_SPEED_LIMIT 1200.0f
#define ANGULAR_DAMPENING_FACTOR 0.991f
#define STRAIGHTEN_THRUST NON_DIRECT_THRUST*3.0f
#define PLAYER_TARGETING_TYPE cLeviathanComponent

#define MISSILE_SLOTS 5

#define FLAME_TRAIL_PROBABILITY 0.95f
#define FLAME_TRAIL_SCATTER 10.0f
#define FLAME_TRAIL_DAMAGE_LIMIT PLAYER_BULLET_DAMAGE*0.9f

#define MAP_SIZE 10.0f
#define MAP_SCALE 1.0f/600.0f
#define MAP_LARGEST_SIZE sqrt(MAP_SIZE*MAP_SIZE)
#define MAP_DISPLAY_X 0.0f
#define MAP_DISPLAY_Y (mpCamera->Height()/1.5)
#define MAP_DISPLAY_Z (mpCamera->Near()+MAP_LARGEST_SIZE*1.1)

//Player Input Settings
#define KEY_TAP_TIME 0.5f

#define TARGETING_INPUT (KEY_t)
#define THRUST_CHANGE_INPUT (_MOUSE->Right())
#define BULLETS_FIRE_INPUT (_MOUSE->Left())
#define SLIDE_UP_INPUT (KEY_w)
#define SLIDE_DOWN_INPUT (KEY_s)
#define SLIDE_LEFT_INPUT (KEY_d)
#define SLIDE_RIGHT_INPUT (KEY_a)
#define BEAM_FIRE_INPUT (KEY_SPACE)
#define SLIDE_KEY_INPUT (KEY_SHIFT)
#define BRAKE_KEY_INPUT (KEY_CAPSLOCK)
#define TOGGLE_ZOOM_VIEWPORT (KEY_CTRL)
#define MISSILE_LAUNCH_KEY (KEY_m)
#define TOGGLE_SOUND (KEY_k)
#define TOGGLE_MISSILE_SELECTED (KEY_n)
#define DISPLAY_MISSILE_RACK (KEY_b)

#define PLANNING_COMPONENT_SELECT (KEY_w)
#define PLANNING_LEVIATHAN_ROTATE (_MOUSE->Left())
#define PLANNING_CAMERA_ROTATE (KEY_SHIFT)
#define PLANNING_CAMERA_ROTATE_SPEED 0.001f
#define PLANNING_CAMERA_ADVANCE (KEY_SBO)
#define PLANNING_CAMERA_RETREAT (KEY_SBC)
#define PLANNING_TOGGLE_HULL_ICONS (KEY_p)
#define PLANNING_TOGGLE_UNSELECTED_ICONS (KEY_o)
#define PLANNING_TOGGLE_UNSELECTED_SHIELD (KEY_i)
#define PLANNING_TOGGLE_ARC_RANGE (KEY_k)
#define PLANNING_MESSAGE_DURATION 4.0f

#define PLANNING_SHOW_HULL_ICONS_START 0
#define PLANNING_SHOW_UNSELECTED_ICONS_START 1


#define PITCH_N_ROLL 0
#define MOUSE_SPEED_CONTROL 0

#define BULLET_MISSILE_INTERACTION_DISTANCE 36.0f



#endif
